### ISSUE TITLE
[Atividade #1] Análise Exploratória de Dados

### ISSUE THREAD

**Issue by carlos-stefano** [atlantico-academy/equipe8-2024.3#2]
Criar um notebook de análise exploratória `notebooks/01-exploratory_data_analysis.ipynb`, contendo as seguintes seções de texto:

 - [x] #3
 - [x] #4
 - [x] #5

**Comment by couldbeElex** [comment]
Descrição dos dados e criação de perguntas e hipóteses (#4) feita e enviada. @carlos-stefano, @fiuzatayna 

Restam os insights agora :)

**Comment by couldbeElex** [comment]
Insights concluídos, descrição corrigida e perguntas e hipóteses editadas para melhor representar os novos insights. @carlos-stefano @fiuzatayna
